version: "3"
services:
  mysql:
    image: mysql:5.7
    ports:
      - 33306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  redis:
    image: redis:6.0-alpine
    ports:
      - 63799:6379
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: ./entrypoint.sh
    tty: true
    volumes:
      - .:/app:cached
      - rails_bundle:/app/vendor
      - rails_log:/app/log
      - /app/tmp
    depends_on:
      - mysql
      - redis
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MYSQL_HOST: mysql
      REDIS_HOST: redis
volumes:
  mysql-data:
  rails_bundle:
  rails_log:
