FROM ruby:3.0.2-slim

# NOTE: 日本語環境にする
RUN apt-get update \
  && apt-get install -y locales \
  && echo "ja_JP UTF-8" > /etc/locale.gen \
  && locale-gen
ENV LANG="ja_JP.UTF-8" \
    LANGUAGE="ja_JP:ja" \
    LC_ALL="ja_JP.UTF-8"

# FIXME: build-essential ではなく必要なものだけを入れたい
RUN apt-get install -y build-essential curl libmariadb-dev git vim

RUN gem install -f bundler

RUN mkdir /app
WORKDIR /app
